// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Per-rep scalar trace + convergence verdict for a feature defined by an energy window and a statistic. The agent identifies a feature on the spectrum (white-line peak, pre-edge shoulder, dip between oscillations, etc.) and passes the numeric eV bounds and the statistic that captures it. Returns running mean, running SEM, and a verdict (converged / marginal / needs_more) for that scalar. This is the publication-quality test: the feature SEM should be a small fraction of its mean and the running mean should be flat rep-over-rep.",
  args: {
    "file_name": tool.schema.string().describe("SPEC file name."),
"e_min": tool.schema.number().describe("Lower bound (eV) of the feature window. REQUIRED."),
"e_max": tool.schema.number().describe("Upper bound (eV) of the feature window. REQUIRED."),
"statistic": tool.schema.string().optional().describe("Reduction over the window. 'max' = white-line height. 'argmax' = white-line energy / edge position. 'integral' = peak area. 'min' / 'argmin' = a dip's value / position. 'height' = max - min in window (peak prominence). 'mean' / 'median' = average value (use when the feature is a plateau)."),
"sem_threshold_frac": tool.schema.number().optional().describe("Target final SEM as a fraction of the running mean. 0.01 (1%) is the default for publication-quality on a prominent feature; tighten to 0.005 for very small features driving a result."),
"drift_threshold_frac": tool.schema.number().optional().describe("Step-to-step running-mean drift target as fraction of the latest mean."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "tool",
      "analyze-feature-evolution",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'analyze_feature_evolution' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
