// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Comprehensive scan repetition efficiency report. Includes convergence, CV analysis, rate-based and counts-based Poisson floor comparison, optimal scan count recommendation, and a verdict (needs_more / reasonable / marginal / wasteful). e_min/e_max bounds are required \u2014 whole-spectrum mode averages dynamic content with normalization-defined plateaus and produces structurally optimistic verdicts.",
  args: {
    "file_name": tool.schema.string().optional().describe("SPEC file name. If omitted, uses the most recent file."),
"e_min": tool.schema.number().describe("Lower bound (eV) of the feature window."),
"e_max": tool.schema.number().describe("Upper bound (eV) of the feature window."),
"include_poisson_floor": tool.schema.boolean().optional().describe("If true (default), also compute the absolute counts-based Poisson floor from the raw active counter. Result includes counts_poisson_floor_pct and cv_vs_floor_ratio: ratio ~1 means at the floor (more reps still help as 1/sqrt(n)); ratio >>1 means systematics-limited (more reps won't help)."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "tool",
      "analyze-efficiency",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'analyze_efficiency' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
