// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Run a SPEC macro in a disposable, network-isolated sandbox container. Returns JSON with an 'output' key containing the clean command result and a 'log' key with the full session transcript (startup noise included). Use 'output' for parsing; use 'log' only for debugging. Each call is a cold start: no state persists between calls. Sim-only \u2014 does not affect real hardware. Always check 'output' even on ok=True; SPEC sometimes exits 0 despite warnings.",
  args: {
    "macro": tool.schema.string().describe("SPEC macro source to evaluate. Single command, sequence, or full def block. Do not include a trailing 'exit'."),
"preload": tool.schema.array(tool.schema.string()).optional().describe("Optional filenames under /usr/local/lib/spec.d/ to qdo before running the macro (e.g. 'beamline_align.mac'). Plain filenames only \u2014 no path components."),
"timeout_s": tool.schema.number().optional().describe("Hard kill timeout for the SPEC run in seconds (default 30). Sim mode skips real motion so most runs finish in under a second."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "evaluate_spec_macro"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'evaluate_spec_macro' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
