// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Run a SPEC macro in a disposable, network-isolated sandbox container. Returns JSON with an 'output' key containing the clean command result and a 'log' key with the full session transcript (startup noise included). Use 'output' for parsing; use 'log' only for debugging. Each call is a cold start: no state persists between calls. Sim-only \u2014 does not affect real hardware. Always check 'output' even on ok=True; SPEC sometimes exits 0 despite warnings.",
  args: {
    "macro": tool.schema.string().describe("SPEC macro source to evaluate. Single command, sequence, or full def block. Do not include a trailing 'exit'."),
"preload": tool.schema.array(tool.schema.string()).optional().describe("Optional filenames under /usr/local/lib/spec.d/ to qdo before running the macro (e.g. 'beamline_align.mac'). Plain filenames only \u2014 no path components."),
"timeout_s": tool.schema.number().optional().describe("Hard kill timeout for the SPEC run in seconds (default 30). Sim mode skips real motion so most runs finish in under a second."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "tool",
      "evaluate-spec-macro",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'evaluate_spec_macro' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
