// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Return the per-sample/spot/filter/n_scans plan that Data Collection executes against. Synthesizes from ExperimentPlan.plan_json plus SamplePosition rows (filter_count = xas_filter, counts_per_sec = survey_counts_per_sec). planned_scans_total comes from plan_json when set, falling back to xas_reps.",
  args: {
    "sample_holder_id": tool.schema.string().optional().describe("Optional; defaults to the active holder."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "db",
      "get-comprehensive-collection-plan",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'get_comprehensive_collection_plan' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
