// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Read the current tracking anchor from the SPEC session: stored energy, m1vert/Tz (and their 1/2 constituents), crystal id, and SPEAR steering offset captured at anchor time. Also reports whether SPEAR has visibly drifted since the anchor was set, or whether the crystal set has changed (which would invalidate the anchor for the current geometry).",
  args: {
    // no args
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "get_anchor"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'get_anchor' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
