// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Return every CollectionScan for the currently-active sample. The active sample is the lowest-queue-order entry in plan_json's sample_queue whose status is not 'done' (or the explicit 'active_sample_id' plan flag, if set). Pass 'sample_id' to override the auto-detect.",
  args: {
    "sample_id": tool.schema.string().optional().describe("Override auto-detected active sample."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "db",
      "get-scans-for-active-sample",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'get_scans_for_active_sample' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
