// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Return the per-sample/spot/filter/n_scans plan that Data Collection executes against. Synthesizes from ExperimentPlan.plan_json plus SamplePosition rows (filter_count = xas_filter, counts_per_sec = survey_counts_per_sec). planned_scans_total comes from plan_json when set, falling back to xas_reps.",
  args: {
    "sample_holder_id": tool.schema.string().optional().describe("Optional; defaults to the active holder."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "get_comprehensive_collection_plan"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'get_comprehensive_collection_plan' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
