// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Knife-edge scan to measure horizontal and vertical beam FWHM. Multi-minute. Removes filters and ensures DATAFILE=alignment. Each axis can be measured in 'big' (false, ~mm-scale beam) or 'small' (true, ~50um focused) mode; wrong mode produces artifacts. Standard LiSA configuration is small_x=false, small_z=false.",
  args: {
    "justification": tool.schema.string().describe("REQUIRED for any SPEC-mutating action. Explain in one sentence why you are taking this action right now (will be stored in action_log). Empty / missing justifications are rejected."),
"small_x": tool.schema.boolean().optional().describe("True for tightly-focused horizontal beam (~50um); false (default) for big-beam benders."),
"small_z": tool.schema.boolean().optional().describe("True for tightly-focused vertical beam (~50um); false (default) for big-beam benders."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "measure_beam_size"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'measure_beam_size' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
