// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "General-purpose plotting tool. Plot any data as a line chart. Use this to visualize results from other tools (e.g. read_scan). Supports multiple series on one plot.",
  args: {
    "x": tool.schema.array(tool.schema.number()).describe("X-axis values."),
"y": tool.schema.array(tool.schema.number()).describe("Y-axis values (same length as x)."),
"y2": tool.schema.array(tool.schema.number()).optional().describe("Optional second series Y values."),
"y3": tool.schema.array(tool.schema.number()).optional().describe("Optional third series Y values."),
"y4": tool.schema.array(tool.schema.number()).optional().describe("Optional fourth series Y values."),
"xlabel": tool.schema.string().optional().describe("X-axis label."),
"ylabel": tool.schema.string().optional().describe("Y-axis label."),
"title": tool.schema.string().optional().describe("Plot title."),
"labels": tool.schema.array(tool.schema.string()).optional().describe("Legend labels for each series."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "plot_data"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'plot_data' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
