// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "General-purpose plotting tool. Plot any data as a line chart. Use this to visualize results from other tools (e.g. read_scan). Supports multiple series on one plot.",
  args: {
    "x": tool.schema.array(tool.schema.number()).describe("X-axis values."),
"y": tool.schema.array(tool.schema.number()).describe("Y-axis values (same length as x)."),
"y2": tool.schema.array(tool.schema.number()).optional().describe("Optional second series Y values."),
"y3": tool.schema.array(tool.schema.number()).optional().describe("Optional third series Y values."),
"y4": tool.schema.array(tool.schema.number()).optional().describe("Optional fourth series Y values."),
"xlabel": tool.schema.string().optional().describe("X-axis label."),
"ylabel": tool.schema.string().optional().describe("Y-axis label."),
"title": tool.schema.string().optional().describe("Plot title."),
"labels": tool.schema.array(tool.schema.string()).optional().describe("Legend labels for each series."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "tool",
      "plot-data",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'plot_data' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
