// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Read a single motor's current position (parsed float).",
  args: {
    "motor": tool.schema.string(),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "read_motor_position"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'read_motor_position' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
