// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "This command will call the _xas macro function for spectrum collection based on the element set by select_element. All args get passed onto the <El>_xas func: \"<El>_xas  cntSec  nbrScan  emission  nbrFilter\". Null value for cntSec defaults to 1s, nbrScan to 1, if emission is zero the emiss is not moved, if nbrFilter <0 then filter motor isnt moved. Optional 'element' arg first runs select_element(<element>) for the convenience of single-call element switching.",
  args: {
    "justification": tool.schema.string().describe("REQUIRED for any SPEC-mutating action. Explain in one sentence why you are taking this action right now (will be stored in action_log). Empty / missing justifications are rejected."),
"element": tool.schema.string().optional().describe("Optional. If provided, runs select_element(<element>) before the XAS scan (sets energy, emiss, ROI, plot-selected counter). E.g. 'Fe', 'Cu', 'Au'. Omit if the element is already set."),
"count_time": tool.schema.number().optional().describe("cntSec \u2014 null defaults to 1 s."),
"n_reps": tool.schema.number().optional().describe("nbrScan \u2014 null defaults to 1."),
"emission_ev": tool.schema.number().optional().describe("emission \u2014 0 leaves emiss motor unchanged."),
"filter": tool.schema.number().optional().describe("nbrFilter \u2014 value <0 leaves filter motor unchanged."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "spec-write",
      "run-xas",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'run_xas' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
