// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "d2scan \u2014 relative scan of two motors moving in lockstep, each spanning the same delta range over the same number of points. Common use: map a sample's footprint in the Sx/Sy plane to find its edges (the staple of auto_sample_align's per-sample boundary detection). Default range is \u00b18. NOTE: the 'cen' scan-followup command does not work properly on a d2scan (2D scan) \u2014 do not rely on 'post_scan_move' with mode='cen' after this scan; compute the center yourself and move explicitly instead.",
  args: {
    "justification": tool.schema.string().describe("REQUIRED for any SPEC-mutating action. Explain in one sentence why you are taking this action right now (will be stored in action_log). Empty / missing justifications are rejected."),
"motor1": tool.schema.string().describe("First motor (e.g. 'Sx')."),
"motor2": tool.schema.string().describe("Second motor (e.g. 'Sy')."),
"npoints": tool.schema.number(),
"count_time": tool.schema.number().describe("Seconds per point."),
"delta": tool.schema.number().optional().describe("Symmetric shorthand for 'delta_lo=-delta, delta_hi=+delta'. Mutually exclusive with 'delta_lo'/'delta_hi' \u2014 pass either 'delta' alone, or 'delta_lo'+'delta_hi', not both."),
"delta_lo": tool.schema.number().optional().describe("Lower delta bound. Applied to both motors. Default -8."),
"delta_hi": tool.schema.number().optional().describe("Upper delta bound. Applied to both motors. Default 8."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "spec-write",
      "run-diagonal-scan",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'run_diagonal_scan' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
