// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Save a markdown plan to the project's logs/plans/ directory. Use this at the start of a beamline-optimization session (or any multi-step task) to persist the step-by-step plan you generated, so future sessions can review what was attempted and why.",
  args: {
    "filename": tool.schema.string().describe("Filename for the plan. Must end with .md and contain only alphanumerics, underscore, hyphen, dot. No path separators or directory traversal."),
"content": tool.schema.string().describe("Markdown body of the plan."),
"overwrite": tool.schema.boolean().optional().describe("If false (default), refuse to write when the file already exists. Set true to overwrite an existing plan."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "tool",
      "save-plan",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'save_plan' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
