// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Save a markdown plan to the project's logs/plans/ directory. Use this at the start of a beamline-optimization session (or any multi-step task) to persist the step-by-step plan you generated, so future sessions can review what was attempted and why.",
  args: {
    "filename": tool.schema.string().describe("Filename for the plan. Must end with .md and contain only alphanumerics, underscore, hyphen, dot. No path separators or directory traversal."),
"content": tool.schema.string().describe("Markdown body of the plan."),
"overwrite": tool.schema.boolean().optional().describe("If false (default), refuse to write when the file already exists. Set true to overwrite an existing plan."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "save_plan"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'save_plan' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
