// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Set a default per-sample time budget for an entire sample holder. Stored under the plan's holder_budgets so new samples inherit it; when apply_to_existing=true (default), existing samples on that holder also get the new count_time/reps.",
  args: {
    "holder_id": tool.schema.string().optional().describe("Leave blank to apply to every holder."),
"count_time_s": tool.schema.number().optional(),
"reps": tool.schema.number().optional(),
"mode": tool.schema.string().optional(),
"apply_to_existing": tool.schema.boolean().optional(),
"reason": tool.schema.string().optional(),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "set_holder_time_budget"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'set_holder_time_budget' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
