// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

export default tool({
  description: "Adjust the time budget for a single sample \u2014 change either the per-repetition count time or the number of reps (or both). Optionally restrict to one mode ('xas' or 'emiss').",
  args: {
    "sample_id": tool.schema.string(),
"count_time_s": tool.schema.number().optional().describe("Per-point count time in seconds."),
"reps": tool.schema.number().optional().describe("Number of repetitions."),
"mode": tool.schema.string().optional().describe("Restrict the change to this mode (optional)."),
"reason": tool.schema.string().optional().describe("Short rationale; written to the plan edit log."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args ?? {})
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, `${context.directory}/scripts/tool_dispatcher.py`, "set_sample_time_budget"],
          { cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" },
        )
        proc.stdin.write(payload)
        proc.stdin.end()
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'set_sample_time_budget' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
