// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Adjust the time budget for a single sample. Tweak any of: per-rep count_time_s, total reps, reps_per_spot (int = even split, list[int] = explicit per-spot), n_spots. Optionally restrict to one mode ('xas' or 'emiss').",
  args: {
    "sample_id": tool.schema.string(),
"count_time_s": tool.schema.number().optional().describe("Per-point count time in seconds."),
"reps": tool.schema.number().optional().describe("Total number of repetitions across all spots."),
"reps_per_spot": tool.schema.string().optional().describe("Either an integer (even split: every spot gets this many) or a list of integers (explicit per-spot reps; length implies n_spots and total reps = sum)."),
"n_spots": tool.schema.number().optional().describe("Number of spots to visit on this sample."),
"mode": tool.schema.string().optional().describe("Restrict the change to this mode (optional)."),
"reason": tool.schema.string().optional().describe("Short rationale; written to the plan edit log."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "db",
      "set-sample-time-budget",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'set_sample_time_budget' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
