// AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
import { tool } from "@opencode-ai/plugin"

// Convert an args dict into argparse-style ["--key", "value", ...] argv.
// Arrays and objects are JSON-encoded as a single string (the Python
// side's _json_arg type converter decodes them).
function flagify(args: Record<string, unknown> | undefined): string[] {
  if (!args) return []
  const out: string[] = []
  for (const [k, v] of Object.entries(args)) {
    if (v === undefined || v === null) continue
    const flag = `--${k.replace(/_/g, "-")}`
    if (typeof v === "boolean") { out.push(flag, v ? "true" : "false"); continue }
    if (typeof v === "number") { out.push(flag, String(v)); continue }
    if (typeof v === "string") { out.push(flag, v); continue }
    out.push(flag, JSON.stringify(v))
  }
  return out
}

export default tool({
  description: "Enable or disable energy tracking. When enabled, every energy move also drives m1vert and Tz so the focused beam stays at the anchor position as the mono Bragg angle changes. Requires set_anchor to have been called first -- without an anchor, tracking has no reference and the beam will drift. Disable before procedures that should leave m1vert/Tz untouched (e.g. independent KB-mirror alignment).",
  args: {
    "justification": tool.schema.string().describe("REQUIRED for any SPEC-mutating action. Explain in one sentence why you are taking this action right now (will be stored in action_log). Empty / missing justifications are rejected."),
"enabled": tool.schema.boolean().describe("True to enable tracking, false to disable."),
  },
  async execute(args, context) {
    const role = process.env.OPENCODE_AGENT_ROLE
    const pyCandidates = [
      `${context.directory}/venv/bin/python3`,
      "python3",
    ]
    const baseArgv = [
      `${context.directory}/scripts/beamtimehero`,
      ...(role ? [role] : []),
      "spec-write",
      "tracking",
      ...flagify(args as Record<string, unknown>),
    ]
    let lastErr = ""
    for (const py of pyCandidates) {
      try {
        const proc = Bun.spawn(
          [py, ...baseArgv],
          { cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" },
        )
        const out = await new Response(proc.stdout).text()
        const err = await new Response(proc.stderr).text()
        const code = await proc.exited
        if (code !== 0) {
          lastErr = `tool 'tracking' failed (exit ${code}): ${err || out}`
          continue
        }
        return out.trim() || "{}"
      } catch (e) {
        lastErr = String(e)
      }
    }
    return JSON.stringify({ ok: false, error: lastErr || "no python found" })
  },
})
