"""Generate one `.opencode/tools/<name>.ts` file per tool in our Python registry.

opencode discovers tools by scanning `.opencode/tools/`. Each tool is a
TypeScript module that declares its schema + calls `Bun.spawn(...)` to
execute `scripts/beamtimehero <category> <kebab-name> --flag value ...`,
the same CLI Claude Code subagents use. We autogenerate them so there's
a single source of truth for the tool surface (the Python `TOOL_DEFINITIONS`)
and so the agent-branch defense layer applies uniformly to both backends.

The generated wrapper:
  • Bakes the tool's category (`tool`/`db`/`spec-read`/`spec-write`) and
    kebab-case CLI name in at generation time.
  • Reads `OPENCODE_AGENT_ROLE` at execute time. When set, the wrapper
    invokes `beamtimehero <role> <category> <kebab-name> ...` so the
    role's spec_write_tools / motor allowlist apply.
  • Converts the args dict into argparse `--flag value` argv. Arrays and
    objects are JSON-encoded as a single string arg (the Python side
    decodes them via `_json_arg`).

Run this once at deploy time (or from `scripts/start.sh`).
"""

from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

# Import orchestration first so its CAT-8 plan tools register into the
# beamline_tools catalog before we read TOOL_DEFINITIONS.
import orchestration  # noqa: F401, E402

from beamline_tools.tool_catalog import TOOL_DEFINITIONS  # noqa: E402
from beamline_tools.tool_catalog.lineage import TOOL_LINEAGE  # noqa: E402


OPENCODE_TOOLS_DIR = ROOT / ".opencode" / "tools"
OPENCODE_TOOLS_DIR.mkdir(parents=True, exist_ok=True)


def _categorize(tool_def: dict) -> str:
    """Mirror of `_categorize()` in scripts/beamtimehero.

    Derives the CLI subtree for a tool from its lineage metadata + required
    params. Must stay in sync with that function so the wrapper invokes the
    same leaf the CLI itself registers.
    """
    name = tool_def["function"]["name"]
    lineage = TOOL_LINEAGE.get(name) or {}
    if lineage.get("source") == "autonomy_db":
        return "db"
    params = tool_def["function"].get("parameters", {}) or {}
    required = set(params.get("required", []) or [])
    if "justification" in required:
        return "spec-write"
    if lineage.get("spec_command") is not None:
        return "spec-read"
    return "tool"


def _schema_for(prop: dict) -> str:
    """Turn a JSONSchema property into a `tool.schema.*` fragment.

    Note: opencode (zod v4) chokes on `tool.schema.any()` when it tries
    to JSON-Schema-ify the args, and on the v3-style `record(value)`
    one-arg form. We avoid both: arrays use a typed item schema (default
    `string()`) and objects are sent as JSON-encoded strings (the Python
    side parses them).
    """
    t = prop.get("type", "string")
    if "enum" in prop:
        return "tool.schema.string()"
    if t == "integer" or t == "number":
        return "tool.schema.number()"
    if t == "boolean":
        return "tool.schema.boolean()"
    if t == "array":
        items = prop.get("items") or {}
        item_t = items.get("type", "string")
        if item_t in ("integer", "number"):
            return "tool.schema.array(tool.schema.number())"
        if item_t == "boolean":
            return "tool.schema.array(tool.schema.boolean())"
        return "tool.schema.array(tool.schema.string())"
    if t == "object":
        return "tool.schema.string()"
    return "tool.schema.string()"


def render_tool_ts(name: str, description: str, params: dict, category: str) -> str:
    props = (params or {}).get("properties", {}) or {}
    required = set((params or {}).get("required", []) or [])

    arg_lines: list[str] = []
    for key, prop in props.items():
        schema = _schema_for(prop)
        if key not in required:
            schema = f"{schema}.optional()"
        desc = (prop.get("description") or "").replace("`", "'").replace("\n", " ").strip()
        if desc:
            schema = f"{schema}.describe({json.dumps(desc)})"
        arg_lines.append(f"    {json.dumps(key)}: {schema},")

    args_block = "\n".join(arg_lines) or "    // no args"

    desc = (description or name).replace("`", "'").replace("\n", " ").strip()
    escaped_desc = json.dumps(desc)

    kebab_name = name.replace("_", "-")

    ts = textwrap.dedent(f"""\
    // AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
    import {{ tool }} from "@opencode-ai/plugin"

    // Convert an args dict into argparse-style ["--key", "value", ...] argv.
    // Arrays and objects are JSON-encoded as a single string (the Python
    // side's _json_arg type converter decodes them).
    function flagify(args: Record<string, unknown> | undefined): string[] {{
      if (!args) return []
      const out: string[] = []
      for (const [k, v] of Object.entries(args)) {{
        if (v === undefined || v === null) continue
        const flag = `--${{k.replace(/_/g, "-")}}`
        if (typeof v === "boolean") {{ out.push(flag, v ? "true" : "false"); continue }}
        if (typeof v === "number") {{ out.push(flag, String(v)); continue }}
        if (typeof v === "string") {{ out.push(flag, v); continue }}
        out.push(flag, JSON.stringify(v))
      }}
      return out
    }}

    export default tool({{
      description: {escaped_desc},
      args: {{
    {args_block}
      }},
      async execute(args, context) {{
        const role = process.env.OPENCODE_AGENT_ROLE
        const pyCandidates = [
          `${{context.directory}}/venv/bin/python3`,
          "python3",
        ]
        const baseArgv = [
          `${{context.directory}}/scripts/beamtimehero`,
          ...(role ? [role] : []),
          {json.dumps(category)},
          {json.dumps(kebab_name)},
          ...flagify(args as Record<string, unknown>),
        ]
        let lastErr = ""
        for (const py of pyCandidates) {{
          try {{
            const proc = Bun.spawn(
              [py, ...baseArgv],
              {{ cwd: context.directory, stdin: "ignore", stdout: "pipe", stderr: "pipe" }},
            )
            const out = await new Response(proc.stdout).text()
            const err = await new Response(proc.stderr).text()
            const code = await proc.exited
            if (code !== 0) {{
              lastErr = `tool '{name}' failed (exit ${{code}}): ${{err || out}}`
              continue
            }}
            return out.trim() || "{{}}"
          }} catch (e) {{
            lastErr = String(e)
          }}
        }}
        return JSON.stringify({{ ok: false, error: lastErr || "no python found" }})
      }},
    }})
    """)
    return ts


def main() -> None:
    # Clean out old autogenerated files so removed tools don't linger.
    for existing in OPENCODE_TOOLS_DIR.glob("*.ts"):
        if "AUTOGENERATED by scripts/generate_opencode_tools.py" in existing.read_text(errors="ignore"):
            existing.unlink()

    written = 0
    for tool_def in TOOL_DEFINITIONS:
        fn = tool_def.get("function") or {}
        name = fn.get("name")
        if not name:
            continue
        description = fn.get("description", "")
        params = fn.get("parameters") or {}
        category = _categorize(tool_def)
        path = OPENCODE_TOOLS_DIR / f"{name}.ts"
        path.write_text(render_tool_ts(name, description, params, category))
        written += 1

    print(f"wrote {written} opencode tool wrappers to {OPENCODE_TOOLS_DIR}")


if __name__ == "__main__":
    main()
