"""Generate one `.opencode/tools/<name>.ts` file per tool in our Python registry.

opencode discovers tools by scanning `.opencode/tools/`. Each tool is a
TypeScript module that declares its schema + calls `Bun.spawn(...)` to
execute `scripts/tool_dispatcher.py`. We autogenerate them so there's a
single source of truth for the tool surface (the Python `TOOL_DEFINITIONS`
+ `AUTONOMY_TOOL_DEFINITIONS`).

Run this once at deploy time (or from `scripts/start.sh`).
"""

from __future__ import annotations

import json
import os
import sys
import textwrap
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "server"))
sys.path.insert(0, str(ROOT / "beamline_lib"))

from tools import TOOL_DEFINITIONS  # noqa: E402


OPENCODE_TOOLS_DIR = ROOT / ".opencode" / "tools"
OPENCODE_TOOLS_DIR.mkdir(parents=True, exist_ok=True)


def _schema_for(prop: dict) -> str:
    """Turn a JSONSchema property into a `tool.schema.*` fragment."""
    t = prop.get("type", "string")
    if "enum" in prop:
        # opencode-ai schema accepts string enums via .string().
        return "tool.schema.string()"
    if t == "integer":
        base = "tool.schema.number()"
    elif t == "number":
        base = "tool.schema.number()"
    elif t == "boolean":
        base = "tool.schema.boolean()"
    elif t == "array":
        base = "tool.schema.array(tool.schema.any())"
    elif t == "object":
        base = "tool.schema.record(tool.schema.any())"
    else:
        base = "tool.schema.string()"
    return base


def render_tool_ts(name: str, description: str, params: dict) -> str:
    props = (params or {}).get("properties", {}) or {}
    required = set((params or {}).get("required", []) or [])

    # Build the `args` block
    arg_lines: list[str] = []
    for key, prop in props.items():
        schema = _schema_for(prop)
        if key not in required:
            schema = f"{schema}.optional()"
        desc = (prop.get("description") or "").replace("`", "'").replace("\n", " ").strip()
        if desc:
            schema = f"{schema}.describe({json.dumps(desc)})"
        arg_lines.append(f"    {json.dumps(key)}: {schema},")

    args_block = "\n".join(arg_lines) or "    // no args"

    desc = (description or name).replace("`", "'").replace("\n", " ").strip()
    escaped_desc = json.dumps(desc)

    ts = textwrap.dedent(f"""\
    // AUTOGENERATED by scripts/generate_opencode_tools.py — DO NOT EDIT BY HAND
    import {{ tool }} from "@opencode-ai/plugin"

    export default tool({{
      description: {escaped_desc},
      args: {{
    {args_block}
      }},
      async execute(args, context) {{
        const payload = JSON.stringify(args ?? {{}})
        const pyCandidates = [
          `${{context.directory}}/venv/bin/python3`,
          "python3",
        ]
        let lastErr = ""
        for (const py of pyCandidates) {{
          try {{
            const proc = Bun.spawn(
              [py, `${{context.directory}}/scripts/tool_dispatcher.py`, {json.dumps(name)}],
              {{ cwd: context.directory, stdin: "pipe", stdout: "pipe", stderr: "pipe" }},
            )
            proc.stdin.write(payload)
            proc.stdin.end()
            const out = await new Response(proc.stdout).text()
            const err = await new Response(proc.stderr).text()
            const code = await proc.exited
            if (code !== 0) {{
              lastErr = `tool '{name}' failed (exit ${{code}}): ${{err || out}}`
              continue
            }}
            return out.trim() || "{{}}"
          }} catch (e) {{
            lastErr = String(e)
          }}
        }}
        return JSON.stringify({{ ok: false, error: lastErr || "no python found" }})
      }},
    }})
    """)
    return ts


def main() -> None:
    # Clean out old autogenerated files so removed tools don't linger.
    for existing in OPENCODE_TOOLS_DIR.glob("*.ts"):
        if "AUTOGENERATED by scripts/generate_opencode_tools.py" in existing.read_text(errors="ignore"):
            existing.unlink()

    written = 0
    for tool_def in TOOL_DEFINITIONS:
        fn = tool_def.get("function") or {}
        name = fn.get("name")
        if not name:
            continue
        description = fn.get("description", "")
        params = fn.get("parameters") or {}
        path = OPENCODE_TOOLS_DIR / f"{name}.ts"
        path.write_text(render_tool_ts(name, description, params))
        written += 1

    print(f"wrote {written} opencode tool wrappers to {OPENCODE_TOOLS_DIR}")


if __name__ == "__main__":
    main()
