"""Single Python entry point invoked by every `.opencode/tools/*.ts` wrapper.

Given a tool name (argv[1]) and a JSON blob of arguments on stdin, this
script routes to our in-process `execute_tool()` dispatcher and prints
the result as JSON on stdout. Errors go to stderr with a non-zero exit.

The TS wrappers are generated by `scripts/generate_opencode_tools.py`.
"""

from __future__ import annotations

import json
import os
import sys
import traceback
from pathlib import Path


def main() -> None:
    if len(sys.argv) < 2:
        print("usage: tool_dispatcher.py <tool_name> < <json-args>", file=sys.stderr)
        sys.exit(2)
    name = sys.argv[1]

    raw = sys.stdin.read().strip()
    args: dict = {}
    if raw:
        try:
            args = json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"invalid JSON on stdin: {e}", file=sys.stderr)
            sys.exit(2)

    here = Path(__file__).resolve().parent
    root = here.parent
    sys.path.insert(0, str(root))

    # Bootstrap simulation BEFORE bl_config is imported. opencode spawns
    # this script in a fresh process every tool call, so the env vars
    # set by the FastAPI parent don't reach us — bootstrap re-applies them
    # here. Idempotent (no-op if SIMULATION_MODE / SPEC_MOCK are off).
    try:
        import simulation  # type: ignore
        simulation.bootstrap()
    except Exception as e:
        print(f"warning: simulation bootstrap failed: {e}", file=sys.stderr)

    # Touch both configs so env vars (BEAMLINE_TOOLS_DB_PATH,
    # ORCHESTRATION_DB_PATH, SPEC_*) are populated for the subprocess.
    try:
        import beamline_tools.config  # noqa: F401
        import orchestration.config  # noqa: F401
    except Exception as e:
        print(f"warning: could not import package configs: {e}", file=sys.stderr)

    # Load the active experiment's phase from the DB so subprocess calls
    # (spawned by opencode) use the same phase gate as the main server.
    try:
        from beamline_tools.spec import spec_cmd  # noqa: E402
        from orchestration.plan_store.session import get_active_experiment  # noqa: E402
        from orchestration.plan_store.client import get_experiment_plan  # noqa: E402

        exp = get_active_experiment()
        if exp is not None:
            plan = get_experiment_plan(exp.id) or {}
            phase = plan.get("phase") or "setup"
            spec_cmd.set_phase(phase, experiment_id=exp.id)
            print(f"[dispatch] phase={phase} exp={exp.id}", file=sys.stderr)
        else:
            print("[dispatch] no active experiment", file=sys.stderr)
    except Exception as e:
        print(f"warning: could not load active phase: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)

    # Import orchestration before running tools so CAT-8 plan tools are
    # registered into the beamline_tools catalog.
    try:
        import orchestration  # noqa: F401
    except Exception as e:
        print(f"warning: could not import orchestration: {e}", file=sys.stderr)

    try:
        from beamline_tools.tool_catalog.executor import execute_tool  # noqa: E402
    except Exception as e:
        print(f"failed to import tool dispatcher: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(2)

    try:
        text, images = execute_tool(name, args)
    except Exception as e:
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({"ok": False, "error": str(e)}), flush=True)
        sys.exit(1)

    if images:
        # Surface image paths alongside the textual result so the UI can pick
        # them up via OpenCodeClient._extract_image_paths.
        try:
            # Images are returned as base64 PNG strings; persist them to disk so
            # opencode can reference them by path.
            out_dir = root / "data" / "tool_plots"
            out_dir.mkdir(parents=True, exist_ok=True)
            import base64
            from datetime import datetime
            paths: list[str] = []
            for i, b64 in enumerate(images):
                fn = out_dir / f"{name}_{datetime.now():%Y%m%d_%H%M%S_%f}_{i}.png"
                fn.write_bytes(base64.b64decode(b64))
                paths.append(str(fn))
            payload = {"text": text, "plot_path": paths[0] if paths else None, "image_paths": paths}
            print(json.dumps(payload, default=str))
            return
        except Exception as e:
            print(json.dumps({"text": text, "image_error": str(e)}, default=str))
            return
    print(text if isinstance(text, str) else json.dumps(text, default=str))


if __name__ == "__main__":
    main()
